config/routes.rb
Rails.application.routes.draw do

  get 'public_meals/index'
  get 'public_workouts/index'
  
  post '/meals/new', to: 'meals#create'
  # post '/meals/:id/update', to: 'meals#update'
  delete '/meals/:id/destroy', to: 'meals#destroy'
  post '/workouts/new', to: 'workouts#create'

  resources :home
  resources :workouts
  resources :meals
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal.rb
class Meal < ApplicationRecord
    belongs_to :user
    has_one_attached :image, dependent: :destroy
    # image.attach(params[:image])
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :meals
  has_many :workouts
  has_one_attached :avatar
  # avatar.attach(params[:avatar])

end

app/models/workout.rb
class Workout < ApplicationRecord
    belongs_to :user
    has_one_attached :image, dependent: :destroy
    # image.attach(params[:image])
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @user= current_user
  end

  def show
  end

  def new
  end

  def edit
  end

  def destroy
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def index
    @user = current_user
    @meals = @user.meals.order('created_at DESC')
  end

  def show
    @meal = Meal.find(params[:id])
  end

  def new
    @user = current_user
    @meal = Meal.new
  end

  def create
    @user = current_user
    @meal = Meal.new(
      user_id: @user.id,
      image: params[:image],
      meal_type: params[:meal_type],
      meal_name: params[:meal_name],
      calories_consumed: params[:calories_consumed]
    )
    if @meal.save
      redirect_to meals_path(@meal)
    else
      render 'new'
    end
  end

  def edit
    # @user = current_user
    @meal = Meal.find(params[:id])
  end

  def update
    @user = current_user
    @meal = Meal.find(params[:id])
    @meal.update(
      user_id: @user.id,
      image: params[:meal][:image],
      meal_type: params[:meal][:meal_type],
      meal_name: params[:meal][:meal_name],
      calories_consumed: params[:meal][:calories_consumed]
    )
    redirect_to meals_path(@meal)
  end

  def destroy
    @meal = Meal.find(params[:id])
    @meal.destroy
        redirect_to request.referrer
  end
end

app/controllers/public_meals_controller.rb
class PublicMealsController < ApplicationController
  def index
    
    @meals = Meal.order('created_at DESC').includes(:user)
    
  end
end

app/controllers/public_workouts_controller.rb
class PublicWorkoutsController < ApplicationController
  def index
    @workouts=Workout.order('created_at DESC').includes(:user)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private

    def sign_up_params
        params.require(:user).permit(:name, :age, :dob, :height, :weight, :gender, :gym, :email, :password, :password_confirmation, :avatar)
    end

    def account_update_params
        params.require(:user).permit(:name, :age, :dob, :height, :weight, :gender, :email, :gym, :password, :password_confirmation, :current_password, :avatar)
    end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  def index
    @user = current_user
    @workouts = @user.workouts.order('created_at DESC')
  end

  def show
    @workout = Workout.find(params[:id])
  end

  def new
    @user = current_user
    @workout = Workout.new
  end

  def create
    @user = current_user
    @workout = Workout.new(
      user_id: @user.id,
      image: params[:image],
      exercise: params[:exercise],
      muscle: params[:muscle],
      calories_burned: params[:calories_burned],
      sets: params[:sets],
      reps: params[:reps],
      weight_amount: params[:weight_amount],
      workout_date: params[:workout_date]
    )
    if @workout.save
      redirect_to workouts_path(@workout)
    else
      render 'new'
    end
  end

  def edit
    # @user = current_user
    @workout = Workout.find(params[:id])
  end

  def update
    @user = current_user
    @workout = Workout.find(params[:id])
    @workout.update(
      user_id: @user.id,
      image: params[:workout][:image],
      exercise: params[:workout][:exercise],
      muscle: params[:workout][:muscle],
      calories_burned: params[:workout][:calories_burned],
      sets: params[:workout][:sets],
      reps: params[:workout][:reps],
      weight_amount: params[:workout][:weight_amount],
      workout_date: params[:workout][:workout_date]
    )
    redirect_to workouts_path(@workout)
  end

  def destroy
    @workout = Workout.find(params[:id])
    @workout.destroy
        redirect_to request.referrer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/public_meals_helper.rb
module PublicMealsHelper
end

app/helpers/public_workouts_helper.rb
module PublicWorkoutsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/home/destroy.html.erb
<h1>Home#destroy</h1>
<p>Find me in app/views/home/destroy.html.erb</p>

app/views/home/index.html.erb
<div class="container">

<div class="uk-grid-collapse uk-child-width-expand@s uk-text-center" uk-grid>
<div class="uk-card">
<h1 class="profile"></h1>

<%if @user.avatar.attached?%>

<div class="profilepic uk-position-top uk-animation-slide-left-medium">
  <%= image_tag(@user.avatar, style:"border-radius:75%; height:100%; align-content: center" )%>
  <br>
  <br />
  <%=@user.name%>
</div>

    <div>
        <div class="uk-background-muted uk-padding">
         <%=@user.email%>
        </div>
    </div>
    <div>
        <div class="uk-background-primary uk-padding uk-light">
        Gym: <%=@user.gym%>
        </div>
    </div>
    <div>
        <div class="uk-background-muted uk-padding">
        Gender: <%=@user.gender%>
        </div>
    </div>
      <div>
        <div class="uk-background-primary uk-padding uk-light">
        Height: <%=@user.height%> ft
        </div>
    </div>
      <div>
        <div class="uk-background-muted uk-padding">
        Weight: <%=@user.weight%> lbs
        </div>
    </div>

      <div>
        <div class="uk-background-primary uk-padding uk-light">
        D.O.B: <%=@user.dob%>
        </div>
        </div>
    </div>
    </div>

    </div>
</div>


<%else%>

<li>Email: <%=@user.email%></li>
<li>Gym: <%=@user.gym%></li>
<li>Gender: <%=@user.gender%></li>
<li>Height: <%=@user.height%> ft</li>
<li>Weight: <%=@user.weight%> lbs</li>
<li>D.O.B: <%=@user.dob%></li>
<br />
<%end%>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fit Friends</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type => "image/x-icon" %>
  </head>

<body>
<nav class="uk-navbar uk-navbar-container uk-margin">
    <div class="uk-navbar-left">
        <a class="uk-navbar-toggle" uk-navbar-toggle-icon href="#"></a>
    
    <% if user_signed_in? %>
 
    <ul class="uk-nav uk-navbar-dropdown-nav" style="margin-right:10px; padding:5px">
      <div class="button"> 
        <%= link_to "Home", home_index_path(@user), style:"margin:10px" %>
      </div>
      <div class="button">
        <%= link_to "My Meals", meals_path(@meal), style:"margin:10px" %> 
      </div>
      <div class="button">
        <%= link_to "My Workouts", workouts_path(@workout), style:"margin:10px" %> 
      </div>
      <div class="button">
        <%= link_to "Public Lifts", public_workouts_index_path(@workouts), style:"margin:10px"%> 
      </div>
      <div class="button">
        <%= link_to "Publics Eats", public_meals_index_path(@meals), style:"margin:10px"%> 
      </div>
    </div>

    <div class="uk-navbar-right" style="margin-right:30px; padding-right:5px">
      <div class="button">
        <%= link_to 'Edit Profile', edit_user_registration_path, style:"margin:10px" %>
      </div>
      <div class="button">  
        <%= link_to "Logout", destroy_user_session_path, style:"margin:10px", method: :delete%>
      </div>
    </div>
    </ul>
    
    
    <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link', style:"margin:10px"  %> 
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link', style:"margin:10px"  %>
    <% end %>
    </div>
    </div>
</nav>

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    
    
    <%= yield %>
  </body>
</html>

app/views/meals/_mealform.html.erb
<%= form_with model: @meals, url: '/meals/new', local: true do |f|%>

<p>
<%= hidden_field_tag(:user_id, @user) %>
</p>

<p>
<%= f.label :meal_type%><br>
<%= f.select :meal_type, ["breakfast", "lunch", "dinner", "snack", "sweets", "desert"], autocomplete: "meal time"%>
</p>

<p>
<%= f.label :meal_name%><br>
<%= f.text_field :meal_name, autocomplete: "meal name"%>
</p>

<p>
<%= f.label :calories_consumed%><br>
<%= f.text_field :calories_consumed, autocomplete: "calories"%>

<%=f.submit 'submit' %>

<%end%>

app/views/meals/destroy.html.erb
<h1>Meals#destroy</h1>
<p>Find me in app/views/meals/destroy.html.erb</p>

app/views/meals/edit.html.erb
<div class="uk-card uk-card-hover uk-card-default">
<center>

<h1>Edit Meal</h2>

<%= form_with model: @meal, local: true do |f|%>

<p>
<%= hidden_field_tag(:user_id, @user) %>
</p>

<p>
<%= f.label :meal_type%><br>
<%= f.select :meal_type, ["breakfast", "lunch", "dinner", "snack", "sweets", "desert"], autocomplete: "meal time"%>
</p>

<p>
<%= f.label :meal_name%><br>
<%= f.text_field :meal_name, autocomplete: "meal name"%>
</p>

<p>
<%= f.label :image%>
<%= f.file_field :image%>
</p>

<p>
<%= f.label :calories_consumed%><br>
<%= f.text_field :calories_consumed, autocomplete: "calories"%>


<%=f.submit 'submit' %>


<%end%>
</center>
</div>

app/views/meals/index.html.erb
<%= link_to "New Meal", new_meal_path(@meal), style:"margin:30px" %>


<%@meals.each do |meal|%>
<div class="uk-card uk-card-hover uk-card-default uk-animation-fade">

<% if meal.image.attached? %>
<div class="uk-postion-left">
    <%=image_tag(meal.image, style:"height:16rem; width:16rem; margin:20px; box-shadow: .1rem .1rem .1rem .1rem #1e87f0")%>
</div>

<ul>
    <div class="uk-position-center">
        <h2><%=meal.meal_name%></h2>
        <li><%=meal.meal_type%></li>
        <li><%=meal.calories_consumed%> calories</li>
        <li><%=meal.created_at.strftime('%B %-d, %Y')%></li>
    </div>
<br />
    <div class="button">
    <%= link_to "Edit", edit_meal_path(meal), style:"margin:10px" %>
    </div>
    <div class="button">
    <%= link_to "Delete", meal_path(meal), method: :delete, style:"margin:10px" %>
    </div>
<%else%>
<center>
    <h2><%=meal.meal_name%></h2>
    <li><%=meal.meal_type%></li>
    <li><%=meal.calories_consumed%> calories</li>
    <li><%=meal.created_at.strftime('%B %-d, %Y')%></li>

<br />
    <div class="button">
    <%= link_to "Edit", edit_meal_path(meal), style:"margin:10px" %>
    </div>
    <div class="button">
    <%= link_to "Delete", meal_path(meal), method: :delete, style:"margin:10px" %>
    </div>
</center>

<%end%>

</div>
</ul>

<%end%>

app/views/meals/new.html.erb
<div class="uk-card uk-card-hover uk-card-default">
<center>
<h1>New Meal</h1>

<%# <render partial: 'mealform' %> 

<%= form_with model: @meals, local: true do |f|%>

<p>
<%= hidden_field_tag(:user_id, @user) %>
</p>

<p>
<%= f.label :meal_type%><br>
<%= f.select :meal_type, ["breakfast", "lunch", "dinner", "snack", "sweets", "desert"], autocomplete: "meal time"%>
</p>

<p>
<%= f.label :meal_name%><br>
<%= f.text_field :meal_name, autocomplete: "meal name"%>
</p>

<p>
<%= f.label :image%>
<%= f.file_field :image%>
</p>

<p>
<%= f.label :calories_consumed%><br>
<%= f.text_field :calories_consumed, autocomplete: "calories"%>
</p>


<%=f.submit 'submit' %>



<%end%>
</center>
</div>

app/views/meals/show.html.erb
<%= link_to "New Meal", new_meal_path(@meal) %>
<div class="uk-card uk-card-hover uk-card-default uk-animation-fade">
<center>

<%if @meal.image.attached?%>
<div style="width:400px; height:400px">
<%=image_tag(@meal.image, style:'width:auto')%>
</div>

<div>
<h2>Name of Meal: <%=@meal.meal_name%></h2>
</div>

<div>
<p>Type of Meal: <%=@meal.meal_type%></p>
</div>

<div>
<p>Total Calories: <%=@meal.calories_consumed%></p>
</div>

<div>
<p>Date:<%=@meal.created_at%></p>
</div>
<%else%>

<div>
<h2>Name of Meal: <%=@meal.meal_name%></h2>
</div>

<div>
<p>Type of Meal: <%=@meal.meal_type%></p>
</div>

<div>
<p>Total Calories: <%=@meal.calories_consumed%></p>
</div>

<div>
<p>Date:<%=@meal.created_at%></p>
</div>

<%end%>
<%= link_to "Edit Meal", edit_meal_path(@meal) %>
</center>
</div>

app/views/public_meals/index.html.erb
<%@meals.each do |meal|%>
<div class="uk-card uk-card-hover uk-card-default uk-animation-fade">
<center>
<ul>
<% if meal.image.attached? %>
<h2><%=meal.meal_name%></h2>
<div class="uk-position-left" style="height:10rem; width:10rem; margin:20px">

<%=image_tag(meal.user.avatar, style:"border-radius:75%; height:100%; align-content: center")%>
<br />
<br />
<%=meal.user.name%>
</div>
<div style="width:300px; height:300px">

<%=image_tag(meal.image, style: 'width:auto', style:"height:16rem; width:16rem; margin:20px; box-shadow: .1rem .1rem .1rem .1rem #1e87f0")%>

<br />

</div>
<li><%=meal.meal_type%></li>
<li><%=meal.calories_consumed%> calories</li>
<li><%=meal.created_at.strftime('%B %-d, %Y')%></li>
<br />


<%else%>
<h2><%=meal.meal_name%></h2>
<li><%=meal.meal_type%></li>
<li><%=meal.calories_consumed%> calories</li>
<li><%=meal.created_at.strftime('%B %-d, %Y')%></li>
<br />


<%end%>
</center>
</div>
</ul>

<%end%>

app/views/public_workouts/index.html.erb
<%@workouts.each do |workout|%>
    <div class="uk-card uk-card-hover uk-card-default uk-animation-fade">
<center>
    <ul>
    <% if workout.exercise? %>
    <h2><%=workout.exercise%></h2>
    <%end%>
<div class="uk-position-left" style="height:10rem; width:10rem; margin:20px">

<%=image_tag(workout.user.avatar, style:"border-radius:75%; height:100%; align-content: center")%>
<br />
<br />
<%=workout.user.name%>
</div>
    <% if workout.image.attached? %>
    <div style="width:16rem; height:16rem">
    <%=image_tag(workout.image,  style:"height:16rem; width:16rem; margin:20px; box-shadow: .1rem .1rem .1rem .1rem #1e87f0")%>
    </div>
    <%end%>
<br />
<br />
        <% if workout.muscle?%>
        <li><%=workout.muscle%></li>
        <%end%>
        <% if workout.calories_burned?%>
        <li><%=workout.calories_burned%> Calories</li>
        <%end%>
        <% if workout.sets? && workout.reps?%>
        <li><%=workout.sets%> Sets x <%=workout.reps%> Reps</li>
        <%end%>
        <% if workout.weight_amount?%>
        <li><%=workout.weight_amount%> Lbs</li>
        <%end%>
        <% if workout.workout_date?%>
        <li><%=workout.workout_date.strftime('%B %-d, %Y')%></li>
        <%end%>
<br />


</center>
</div>
</ul>

<%end%>

app/views/workouts/destroy.html.erb
<h1>Workouts#destroy</h1>
<p>Find me in app/views/workouts/destroy.html.erb</p>

app/views/workouts/edit.html.erb
<div class="uk-card uk-card-hover uk-card-default">
<center>
<h1>Edit Workout</h1>

 
<%= form_with model: @workout, local: true do |f|%>

<p>
<%= hidden_field_tag(:user_id, @user) %>
</p>

<p>
<%= f.label :image%>
<%= f.file_field :image%>
</p>

<p>
<%= f.label :exercise%><br>
<%= f.text_field :exercise, autocomplete: "exercise"%>
</p>

<p>
<%= f.label :muscle%><br>
<%= f.text_field :muscle, autocomplete: "muscle"%>
</p>

<p>
<%= f.label :calories_burned%><br>
<%= f.text_field :calories_burned, autocomplete: "calories"%>
</p>

<p>
<%= f.label :sets%><br>
<%= f.text_field :sets, autocomplete: "sets"%>
</p>

<p>
<%= f.label :reps%><br>
<%= f.text_field :reps, autocomplete: "reps"%>
</p>

<p>
<%= f.label :weight_amount%><br>
<%= f.text_field :weight_amount, autocomplete: "weight amount"%>
</p>

<p>
<%= f.label :workout_date%><br>
<%= f.date_field :workout_date, autocomplete: "workout date"%>
</p>


<%=f.submit 'submit' %>

<%end%>
</center>
</div>

app/views/workouts/index.html.erb
<%= link_to "New Workout", new_workout_path(@workout), style:"margin:30px" %>


<%@workouts.each do |workout|%>
<div class="uk-card uk-card-hover uk-card-default uk-animation-fade">
<center>
    <ul>
    <% if workout.exercise? %>
        <h2><%=workout.exercise%></h2>
        <%end%>
    <div style="uk-position-center">
    <% if workout.image.attached? %>
    <%=image_tag(workout.image, style: "height:16rem; width:16rem; margin:20px; box-shadow: .1rem .1rem .1rem .1rem #1e87f0")%>
    </div>
    <%end%>
    <% if workout.muscle?%>
        <li><%=workout.muscle%></li>
        <%end%>
    <% if workout.calories_burned?%> 
        <li><%=workout.calories_burned%> Calories</li>
        <%end%>
        <% if workout.sets?%>
        <li><%=workout.sets%> Sets</li>
            <%end%>
        <% if workout.reps?%>
        <li><%=workout.reps%> Reps</li>
        <%end%>
        <% if workout.weight_amount?%>
        <li><%=workout.weight_amount%> Lbs</li>
                <%end%>
        <% if workout.workout_date?%>
        <li><%=workout.workout_date.strftime('%B %-d, %Y')%></li>
                <%end%>
                    
             
<br />

        <div class="button">
        <%= link_to "Edit", edit_workout_path(workout), style:"margin:10px" %>
        </div>
        <div class="button">
        <%= link_to "Delete", workout_path(workout), method: :delete, style:"margin:10px" %>
        </div>
        </center>
    </div>
</ul>
<%end%>

app/views/workouts/new.html.erb
<div class="uk-card uk-card-hover uk-card-default">
<center>

<h1>New Workout</h1>

 <%= form_with model: @workouts, url: '/workouts/new', local: true do |f|%>

<p>
<%= hidden_field_tag(:user_id, @user) %>
</p>

<p>
<%= f.label :image%>
<%= f.file_field :image%>
</p>

<p>
<%= f.label :exercise%><br>
<%= f.text_field :exercise, autocomplete: "exercise"%>
</p>

<p>
<%= f.label :muscle%><br>
<%= f.text_field :muscle, autocomplete: "muscle"%>
</p>

<p>
<%= f.label :calories_burned%><br>
<%= f.text_field :calories_burned, autocomplete: "calories"%>
</p>

<p>
<%= f.label :sets%><br>
<%= f.text_field :sets, autocomplete: "sets"%>
</p>

<p>
<%= f.label :reps%><br>
<%= f.text_field :reps, autocomplete: "reps"%>
</p>

<p>
<%= f.label :weight_amount%><br>
<%= f.text_field :weight_amount, autocomplete: "weight amount"%>
</p>

<p>
<%= f.label :workout_date%><br>
<%= f.date_field :workout_date, autocomplete: "workout date"%>
</p>


<%=f.submit 'submit' %>

<%end%>
</center>
</div>

app/views/workouts/show.html.erb
<%= link_to "New Workout", new_workout_path(@workout) %>

<div class="uk-card uk-card-hover uk-card-default uk-animation-fade">
<center>
<%if @workout.image.attached?%>
<div style="width:400px; height:400px">
<%=image_tag(@workout.image, style:'width:100%')%>
</div>




<div>
<h2>Type of workout: <%=@workout.exercise%></h2>
</div>

<div>
<p>Muscle Targeted: <%=@workout.muscle%></p>
</div>

<div>
<p>Total Calories Burned: <%=@workout.calories_burned%></p>
</div>

<div>
<p>Sets / Reps: <%=@workout.sets%> x <%=@workout.reps%></p>
</div>

<div>
<p>Weight Amount: <%=@workout.weight_amount%></p>
</div>

<div>
<p>Date: <%=@workout.workout_date%></p>
</div>
<%else%>

<div>
<h2>Type of workout: <%=@workout.exercise%></h2>
</div>

<div>
<p>Muscle Targeted: <%=@workout.muscle%></p>
</div>

<div>
<p>Total Calories Burned: <%=@workout.calories_burned%></p>
</div>

<div>
<p>Sets / Reps: <%=@workout.sets%> x <%=@workout.reps%></p>
</div>

<div>
<p>Weight Amount: <%=@workout.weight_amount%></p>
</div>

<div>
<p>Date: <%=@workout.workout_date%></p>
</div>

<%end%>

<%= link_to "Edit workout", edit_workout_path(@workout) %>
</center>
</div>